name = "Aeronautics Online"
author = "gelvetica, Aeronautics Online Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5acbf17ff6218ac7d3a497be5ede33ff4e383f4607cfef370817406e957f8759"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
