name = "Aeronautics Online"
author = "gelvetica, Aeronautics Online Contributors"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aea8798b378f5a49e9f5df9aa3a19c149d5d05cbb86304848de9735fa9812e20"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
