name = "Aeronautics Online"
author = "gelvetica, Aeronautics Online Contributors"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80ec9130ae38f3b8972a3bf133a236de09f4028d644edad983c5e5f6b6ea90f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
